DROP TABLE IF EXISTS OFFER;
CREATE TABLE "OFFER" (
    "ID" VARCHAR2(6) NOT NULL PRIMARY KEY,	
	"OFFER_NAME" VARCHAR2(40) NOT NULL,
	"DATE_BEGINING" DATE NOT NULL,
    "DATE_END" DATE NOT NULL,
	"OFFER_DESCRIPTION" VARCHAR2(100) NOT NULL
);